"""add clarification_question to query_history

Revision ID: 4cb1e7fae285
Revises: ed87e84f12c3
Create Date: 2026-08-22 22:51:43.589874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cb1e7fae285'
down_revision: Union[str, Sequence[str], None] = 'ed87e84f12c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_history', sa.Column('clarification_question', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_history', 'clarification_question')
    # ### end Alembic commands ###
