"""add token tracking to query_history

Revision ID: d99a26cccde1
Revises: 4cb1e7fae285
Create Date: 2026-08-26 18:38:57.238087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd99a26cccde1'
down_revision: Union[str, Sequence[str], None] = '4cb1e7fae285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_history', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('query_history', sa.Column('output_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_history', 'output_tokens')
    op.drop_column('query_history', 'input_tokens')
    # ### end Alembic commands ###
