"""add query_cache table and query_history.served_from_cache

Revision ID: e1ddc2a1011e
Revises: fffbac12c7e4
Create Date: 2026-09-03 15:38:43.701849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1ddc2a1011e'
down_revision: Union[str, Sequence[str], None] = 'fffbac12c7e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('question_normalized', sa.Text(), nullable=False),
    sa.Column('sql', sa.Text(), nullable=True),
    sa.Column('is_ambiguous', sa.Boolean(), nullable=False),
    sa.Column('clarification_question', sa.Text(), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('query_history', sa.Column('served_from_cache', sa.Boolean(), nullable=False, server_default='false'))    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_history', 'served_from_cache')
    op.drop_table('query_cache')
    # ### end Alembic commands ###
